config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :holidays, only: [:create]

  resources :blogs

  resources :blog_assignments, only: [:update]

  get 'posts/filter' => 'posts#filter'

  resources :posts

  resources :users

  resources :memberships

  resources :cohorts do 
    resources :schedules
  end

  post 'generate_blog_rotation' => 'schedules#generate_blog_rotation'

  post 'schedules/update_holidays' => 'schedules#update_holidays'

  post 'get_new_posts' => 'cohorts#get_new_posts'

  get 'get_new_posts_for_user' => 'users#get_new_posts'

  patch 'blogs/:id/reset' => 'blogs#reset', as: 'reset_blog'

  post 'set_blog_rotation' => 'schedules#set_blog_rotation'

  match 'login', to: redirect('/auth/github'), via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  
  get 'logout' => 'sessions#destroy'

  get 'publish_post' => 'posts#publish_post'

  get 'feature_post' => 'posts#feature_post'

  get 'publish_posts' => 'posts#publish_posts'

  post 'set_default_holidays' => 'holidays#set_default_holidays'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :cohorts, through: :memberships
  has_many :blogs, dependent: :destroy
  has_many :posts, through: :blogs
  has_many :blog_assignments, dependent: :destroy
  has_many :schedules, through: :cohorts
  
  validates :github_username, :presence => true, :uniqueness => true, length: { maximum: 50 }
  validates :first_name, length: { maximum: 50 }
  validates :last_name, length: { maximum: 50 }
  validates :email, length: { maximum: 50 }

  def self.find_or_create_from_auth_hash(auth)
    where(github_username: auth.info.nickname).first_or_initialize.tap do |user|
      user.access_token = auth.credentials.token
      user.github_username = auth.info.nickname
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.image = auth.info.image
      user.save
    end
  end

  def name
    if first_name && last_name
      first_name + " " + last_name
    end
  end

  def client
    Octokit::Client.new(access_token: access_token, client_id: ENV['github_client_id'], client_secret: ENV['github_client_secret'])
  end

  def full_name_or_github_name
    name || github_username
  end

  def first_name_or_github_name
    first_name || github_username
  end

  def blog
    blogs.first
  end

  def blog_assignments_for_schedule(schedule)
    blog_assignments.where(schedule_id: schedule.id)
  end

  def completed_blog_assignments(schedule)
    blog_assignments_for_schedule(schedule).select { |b| b.completed? }
  end

  def percent_blog_assignments_completed(schedule)
    (completed_blog_assignments(schedule).count.to_f / blog_assignments_for_schedule(schedule).count) * 100
  end

  def next_valid_day(previous_day, days_array, frequency)
    index = days_array.index(previous_day)
    new_index = (index + frequency)
    days_array[new_index]
  end

  def assign_blogs(schedule, current_day_index)
    valid_days = schedule.weekdays_that_arent_holidays
    due_date = valid_days[current_day_index]
    date_index = valid_days.index(due_date)
    until valid_days[date_index] == nil
      schedule.blog_assignments.create(due_date: valid_days[date_index], user_id: id)
      date_index += schedule.frequency
    end
  end

  def blog_posts_written_since_last_assignment_date
    past_assignments = blog_assignments.where("due_date < ?", Date.today.to_date)
    last_assignment = past_assignments.order('due_date DESC').first
    entries = blog.posts_after_date(last_assignment.due_date)
  end

  def blog_posts_written_since_previous_assignment(date, schedule)
    if blog
      past_assignments = blog_assignments_for_schedule(schedule).where("due_date < ?", date)
      last_assignment = past_assignments.order('due_date DESC').first
      last_assignment ? blog.posts_for_range(last_assignment.due_date, date) : blog.posts_for_range(schedule.start_date - 7.days, date) 
    else
      []
    end
  end

  def remaining_blog_assignments
    blog_assignments.where("due_date > current_date")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:create, :index]
  before_action :verify_identity
  
  def create
    @user = User.new(user_params)
    if @user.save
      set_user_cohort
      redirect_to(:back)
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      redirect_to(:back)
    end
  end

  def show
  end

  def edit
    set_from_uri
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Update successful!"
      redirect_to_from_uri
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      redirect_to(:back)
    end
  end

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to(:back)
  end

  def get_new_posts
    @user.blogs.each do |blog|
      blog.create_entries
    end
    flash[:success] = "New posts successfully retrieved!"
    redirect_to(:back)
  end

  private 

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :github_username)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def verify_identity
      if !current_user.admin && @user != current_user
        flash[:alert] = "You're not allowed to see that!"
        redirect_to root_path
      end
    end

    def set_user_cohort
      @cohort = Cohort.find(params[:user][:cohort]) if params[:user][:cohort]
      create_membership
    end

    def create_membership
      Membership.create(user_id: @user.id, cohort_id: @cohort.id) if @cohort
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_delete.html.erb
<%= link_to 'delete', user_path(user), method: 'delete', class: 'btn btn-default btn-xs', data: {confirm: "Are you sure you want to delete this person?"} %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :github_username %>
  <%= f.text_field :github_username, class:"form-control" %>
  </div>
  
  <%= f.hidden_field 'cohort', value: cohort_id %>
  <div class="form-group">
  <%= f.submit class:"form-control" %>
  </div>
<% end %>

app/views/users/_progress.html.erb
<h3>Progress</h3>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @user.percent_blog_assignments_completed(schedule) %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @user.percent_blog_assignments_completed(schedule) %>%;">
    <%= @user.percent_blog_assignments_completed(schedule).round %>%
  </div>
</div>

app/views/users/_remove_from_cohort.html.erb
<%= link_to 'delete', membership_path(Membership.find_by(user_id: user.id, cohort_id: cohort.id)), method: 'delete', class: 'btn btn-default btn-xs', data: {confirm: "Are you sure you want to remove this person from this cohort?"} %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.full_name_or_github_name, user_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= user.github_username %></td>

  <% if user.blog %>
    <td class="extra-margin-bottom">
      <div>
        <%= link_to user.blog.title, user.blog.full_url %>
      </div>
      <%= link_to 'edit', edit_blog_path(user.blog, cohort: cohort), class: 'btn btn-default btn-xs' %>
      <%= link_to 'delete', blog_path(user.blog), method: 'delete', class: 'btn btn-default btn-xs', data: {confirm: "Are you sure you want to delete this blog?"} %>
      <%= link_to 'reset', reset_blog_path(user.blog), method: 'patch', class: 'btn btn-default btn-xs', data: {confirm: "This will delete all associated posts, reset the title and feed url, and fetch new posts. Are you sure?"} %>
    </td>
  <% else %>
    <td>
      <%= render 'blogs/form_for_user_blog', blog: user.blogs.new, user_id: user.id %>
    </td>
  <% end %>

  <% if user.blog && user.blog.posts.any? %>
    <td><%= link_to truncate(user.blog.latest_post.title, length: 30), user.blog.latest_post.url, title: user.blog.latest_post.title %></td>
    <td><%= user.blog.latest_post.published_date.strftime("%m/%d/%Y") %></td>
  <% else %>
    <td> - </td>
    <td> - </td>
  <% end %>

  <td id="edit-or-delete-user">
    <%= link_to 'edit', edit_user_path(user), class: 'btn btn-default btn-xs' %>
    <% if cohort %>
      <%= render 'users/remove_from_cohort', user: user, cohort: @cohort %>
    <% else %>
      <%= render 'users/delete', user: user %>
    <% end %>
  </td>
</tr>

app/views/users/_user_schedule.html.erb
<div class="well">
  <legend>
    <%= link_to schedule.name, cohort_schedule_path(schedule.cohort, schedule) %>
  </legend>
    
  <div class="row">
    <div class="col-md-12">
      <%= render 'progress', schedule: schedule %>
    </div>
  </div>
  <% @user.blog_assignments_for_schedule(schedule).order(:due_date).each do |blog_assignment| %>
    <p class="large-font">
      <% if current_user.admin %>
        <a data-toggle="modal" href="#selectPostModal-<%= blog_assignment.id %>" class="btn btn-default btn-xs">choose post</a>
      <% end %>
      
      <%= render 'schedules/greenlight', blog_assignment: blog_assignment %>
      <%= blog_assignment.due_date.strftime("%A, %m/%d/%Y") %>: 
      <%= blog_assignment.posts_since_previous.collect {|entry| (link_to entry.title, entry.url) + " (#{entry.published_date.strftime("%m/%d/%Y")})" }.to_sentence.html_safe %>
      
      <% if current_user.admin %>
        <%= render 'blog_assignments/select_post_for_blog_assignment_modal', blog_assignment: blog_assignment %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="well">
  <legend>Edit <%= @user.full_name_or_github_name %></legend>

  <%= render 'form', user: @user, cohort_id: nil %>

  <%= link_to 'Cancel', :back %>
</div>

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Github Username</th>
      <th>Blog</th>
      <th>Latest Post</th>
      <th>Published Date</th>
      <th>edit/delete</th>
    </tr>
  </thead>
  <tbody>
    <% @users.all.each do |user| %>
      <%= render 'user', user: user, cohort: nil %>
    <% end %>  
  </tbody>
</table>

app/views/users/show.html.erb
<% if @user.blog && !@user.blog.feed_url %>
  <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Your blog has no feed url!</h4>
    <div class="panel-body">
      <p>
      This could be because your blog was not set up yet. When your blog is set up, click here to set the feed url:

      <%= link_to 'reset', reset_blog_path(@user.blog), method: 'patch', class: 'btn btn-default btn-sm', data: {confirm: "This will delete all associated posts, reset the title and feed url, and fetch new posts. Are you sure?"} %>
      </p>

      <p>
      If your blog is already set up but the 'reset' button did not get the feed url, you can enter it manually here:

      <%= form_for @user.blog, html: {class: 'form-inline'} do |f| %>
        <%= f.text_field :feed_url, placeholder: 'full url including http', pattern: '^htt(p|ps):\/\/.+', class: "form-control" %> 
        <%= f.submit "Submit", class: "btn btn-default btn-sm" %>
      <% end %>
      </p>
    </div>
  </div>
<% end %>

<div class="row extra-margin-bottom">
  <div class="col-md-12">
    <h1>
      <%= @user.full_name_or_github_name %>
      <%= link_to 'Get New Posts', get_new_posts_for_user_path(id: @user.id), class: 'btn btn-success pull-right' %>
      <% if @user == current_user %>
        <%= link_to 'Edit Your Profile', edit_user_path(@user), class: 'btn btn-info pull-right extra-margin-right' %>
      <% end %>
    </h1>
  </div>
</div>

<% @user.schedules.each do |schedule| %>
  <%= render 'user_schedule', schedule: schedule %>
<% end %>

<div class="row">

  <h2 id="blogs-header" class="col-md-1">
    Blogs
  </h2>

  <div id="add-blog" class="col-md-6">
    <%= link_to "Add A Blog", "#", class: 'btn btn-default btn-sm', id: 'toggle-blog-form' %>

    <%= form_for Blog.new, html: {class: 'form-inline', id: 'hidden-blog-form'} do |f| %>
      <%= f.label :url %>
      <%= f.text_field :url, placeholder: 'full url including http', class: 'form-control', pattern:'^htt(p|ps):\/\/.+' %>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.submit class: 'form-control' %>
    <% end %>
  </div>

</div>

<%= render @user.blogs %>