config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :holidays, only: [:create]

  resources :blogs

  resources :blog_assignments, only: [:update]

  get 'posts/filter' => 'posts#filter'

  resources :posts

  resources :users

  resources :memberships

  resources :cohorts do 
    resources :schedules
  end

  post 'generate_blog_rotation' => 'schedules#generate_blog_rotation'

  post 'schedules/update_holidays' => 'schedules#update_holidays'

  post 'get_new_posts' => 'cohorts#get_new_posts'

  get 'get_new_posts_for_user' => 'users#get_new_posts'

  patch 'blogs/:id/reset' => 'blogs#reset', as: 'reset_blog'

  post 'set_blog_rotation' => 'schedules#set_blog_rotation'

  match 'login', to: redirect('/auth/github'), via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  
  get 'logout' => 'sessions#destroy'

  get 'publish_post' => 'posts#publish_post'

  get 'feature_post' => 'posts#feature_post'

  get 'publish_posts' => 'posts#publish_posts'

  post 'set_default_holidays' => 'holidays#set_default_holidays'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :cohort
  has_many :blog_assignments, dependent: :destroy
  has_many :users, through: :cohort

  validate :end_date_is_after_start_date
  validates :name, length: { maximum: 50 }

  accepts_nested_attributes_for :blog_assignments

  WEEKEND_DAYS = ['Saturday', 'Sunday']

  def end_date_is_after_start_date
    errors.add(:end_date, "must be after start date") if end_date <= start_date
  end

  # guarantees that there will be a consistent number of blog assignments on each day, frequency will be approximately what was specified
  def generate_blog_assignments_based_on_users_per_day
    shuffled = cohort.users.shuffle
    counter = 0
    weekdays_that_arent_holidays.each do |day|
      bloggers_per_day.times do
        blog_assignments.create(user_id: shuffled[counter].id, due_date: day)
        counter < (shuffled.length - 1) ? counter += 1 : counter = 0
      end
    end
  end

  # guarantees specified frequency will be adhered to, side effect is sometimes days get skipped or have inconsistent number of students per day
  def generate_blog_assignments
    shuffled = cohort.users.shuffle
    current_day_index = 0
    max_day = weekdays_that_arent_holidays.last
    shuffled.each_with_index do |user, index|
      if index != 0 && index % bloggers_per_day == 0
        current_day_index += 1
      end
      user.assign_blogs(self, current_day_index)
    end
  end

  def posts_per_blogger
    (weekdays_that_arent_holidays.count / frequency)
  end

  def bloggers_per_day
    ((posts_per_blogger * cohort.users.count) / weekdays_that_arent_holidays.count) + 1
  end

  def leftover_posts
    (posts_per_blogger * cohort.users.count) % weekdays_that_arent_holidays.count
  end

  def days
    (start_date..end_date).to_a
  end

  def weekdays
    days.select { |day| !WEEKEND_DAYS.include?(day.strftime("%A")) }
  end

  def weekdays_that_arent_holidays
    weekdays - Holiday.all.pluck(:date)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, except: [:new, :create]
  
  def show
  end

  def new
    @cohort = Cohort.find(params[:cohort_id])
    @schedule = @cohort.schedules.build
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.cohort_id = (params[:cohort_id])
    if @schedule.save
      flash[:notice] = "Schedule successfully created!"
      redirect_to cohort_schedule_path(@schedule.cohort, @schedule)
    else
      flash[:alert] = @schedule.errors.full_messages.to_sentence
      redirect_to(:back)
    end
  end

  def edit
    @cohort = @schedule.cohort
  end

  def update
    if @schedule.update(schedule_params)
      flash[:notice] = "Schedule successfully updated!"
    else
      flash[:alert] = @schedule.errors.full_messages.to_sentence
    end
    redirect_to cohort_schedule_path(@schedule.cohort, @schedule)
  end

  def destroy
    @schedule.destroy
    redirect_to cohort_path(@schedule.cohort)
  end

  def generate_blog_rotation
    @schedule.blog_assignments.all.destroy_all
    @priority = params[:priority]

    if @priority == "adhere to specified frequency"
      @schedule.generate_blog_assignments
    else
      @schedule.generate_blog_assignments_based_on_users_per_day
    end
    
    redirect_to cohort_schedule_path(@schedule.cohort, @schedule)
  end

  def set_blog_rotation
    @schedule.toggle!(:rotation_locked)
    redirect_to(:back)

    if @schedule.rotation_locked
      @schedule.users.each do |user|
        UserMailer.initial_schedule_notification(@schedule, user).deliver_later if user.blog_assignments.any?
      end
    end
  end

  private

    def schedule_params
      params.require(:schedule).permit(:name, :start_date, :end_date, :cohort_id, :frequency, :blog_assignments_attributes => [:user_id, :due_date, :schedule_id, :id])
    end

    def set_schedule
      @schedule = Schedule.find(params[:id])
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_blog_assignments_form.html.erb
<% @schedule.weekdays_that_arent_holidays.each do |day| %>
  <div class="row">

    <h3 class="col-md-12">
      <%= day.strftime("%A, %m/%d") %>
    </h3>

    <div class="form-group">
      <% @schedule.blog_assignments.where(due_date: day).each do |blog_assignment| %>

        <%= f.fields_for :blog_assignments, blog_assignment do |blog_assignment_form| %>

          <div class="form-group">
            <div class="col-md-3">
            <%= blog_assignment_form.collection_select :user_id, @schedule.cohort.users, :id, :full_name_or_github_name, {}, {class: "form-control"} %>
            </div>

            <%= blog_assignment_form.hidden_field :due_date, value: day %>
            <%= blog_assignment_form.hidden_field :schedule_id, value: @schedule.id %>
          </div>

        <% end %>

      <% end %>
    </div>
    
  </div>
<% end %>

app/views/schedules/_day.html.erb
<h3><%= day.strftime("%A, %m/%d") %></h3>

<%= render @schedule.blog_assignments.where(due_date: day) %>

app/views/schedules/_form.html.erb
<%= form_for [@cohort, @schedule] do |f| %>
  <div class="form-group">
    <div class="form-group extra-margin-bottom">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to 'Back', :back, class: 'btn btn-default' %>
    </div>
    <%= f.label :name, 'Schedule Name' %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, class: "form-control", required: true %>
  </div>
  
  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.date_field :end_date, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :frequency %>:
    each person should blog once every <%= f.number_field :frequency, class: "form-control small-field inline", required: true %> school days (for example, enter 5 if they should blog once per week)
  </div>

  <% if @schedule.persisted? %>
    <%= render 'blog_assignments_form', f: f %>
  <% end %>
<% end %>

app/views/schedules/_generate_blog_rotation_form.html.erb
<%= form_tag(generate_blog_rotation_path(id: @schedule.id), {method: :post, class: 'form-inline'}) do %>
  <div class="form-group">
    <%= select_tag "priority", options_for_select(["select a priority", "consistent number of blogs per day", "adhere to specified frequency"], selected: flash[:priority] || "select a priority"), class: 'form-control' %>
    <%= submit_tag 'Generate Blog Rotation', class: 'btn btn-large btn-primary', id: 'generate' %>
  </div>
  <%= render 'set_blog_rotation', schedule: @schedule %>
<% end %>

app/views/schedules/_greenlight.html.erb
<% if blog_assignment.due_date > Date.today %>
  <i class="fa fa-circle-thin"></i>
<% else %>
  <% if blog_assignment.completed? %>
    <i class="fa fa-circle green"></i>
  <% else %>
    <i class="fa fa-circle red"></i>
  <% end %>
<% end %>

app/views/schedules/_schedule.html.erb
<%= link_to schedule.name, cohort_schedule_path(schedule.cohort, schedule), class: "btn btn-info btn-xs" %>
<%= link_to 'x', cohort_schedule_path(schedule.cohort, schedule), method: 'delete', data: {confirm: "Are you sure you want to delete this schedule?"}, class: "btn btn-danger btn-xs" %>

app/views/schedules/_set_blog_rotation.html.erb
<% if @schedule.rotation_locked %>
  <%= link_to 'Unlock Blog Rotation', set_blog_rotation_path(id: @schedule.id), method: 'post', class: 'btn btn-large btn-success', rotation_locked: @schedule.rotation_locked %>
<% else %>
  <%= link_to 'Lock Blog Rotation', set_blog_rotation_path(id: @schedule.id), method: 'post', class: 'btn btn-large btn-danger', rotation_locked: @schedule.rotation_locked %>
<% end %>

app/views/schedules/edit.html.erb
<h2>Edit <%= @schedule.name %></h2>

<%= render 'form' %>

app/views/schedules/new.html.erb
<h2>
  Create a New Blogging Schedule for <%= @cohort.name %> 
</h2>
<%= render 'form' %>

app/views/schedules/show.html.erb
<div class="row extra-margin-bottom">
  <div class="col-md-12">
    <h1><%= @schedule.name %></h1>
    <% if current_user.admin %>
      <%= link_to 'back to cohort page', cohort_path(@schedule.cohort), class: "btn btn-default" %> 
      <%= link_to 'edit this schedule', edit_cohort_schedule_path(@schedule.cohort, @schedule), class: "btn btn-default" %>
      <%= link_to 'get new posts', get_new_posts_path(id: @schedule.cohort.id), class: 'btn btn-large btn-success', method: 'post' %>
    <% end %>
  </div>
</div>

<p>
  <strong>Cohort: </strong>
  <%= @schedule.cohort.name %>
</p>

<p>
  <strong>Start Date: </strong>
  <%= @schedule.start_date.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>End Date: </strong>
  <%= @schedule.end_date.strftime("%m/%d/%Y") %>
</p>

<% if current_user.admin %>
  <p>
    Blogging frequency is once every <%= @schedule.frequency %> days.
  </p>

  <%= render 'generate_blog_rotation_form' %>
<% end %>

<% @schedule.weekdays_that_arent_holidays.each do |day| %>
  <%= render 'day', day: day %>
<% end %>