config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :holidays, only: [:create]

  resources :blogs

  resources :blog_assignments, only: [:update]

  get 'posts/filter' => 'posts#filter'

  resources :posts

  resources :users

  resources :memberships

  resources :cohorts do 
    resources :schedules
  end

  post 'generate_blog_rotation' => 'schedules#generate_blog_rotation'

  post 'schedules/update_holidays' => 'schedules#update_holidays'

  post 'get_new_posts' => 'cohorts#get_new_posts'

  get 'get_new_posts_for_user' => 'users#get_new_posts'

  patch 'blogs/:id/reset' => 'blogs#reset', as: 'reset_blog'

  post 'set_blog_rotation' => 'schedules#set_blog_rotation'

  match 'login', to: redirect('/auth/github'), via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  
  get 'logout' => 'sessions#destroy'

  get 'publish_post' => 'posts#publish_post'

  get 'feature_post' => 'posts#feature_post'

  get 'publish_posts' => 'posts#publish_posts'

  post 'set_default_holidays' => 'holidays#set_default_holidays'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login

  def index
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Blogger</h1>
  <% if current_user %>
    <%= link_to 'Go To Your Profile', user_path(current_user), class: "btn btn-success btn-large" %>
    <%= link_to 'Go To The Admin Dashboard', cohorts_path, class: "btn btn-success btn-large" if current_user.admin %> 
  <% else %>
    <%= link_to 'Sign In With Github', login_path, class: "btn btn-success btn-lg" %>
  <% end %>
</div>