config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :holidays, only: [:create]

  resources :blogs

  resources :blog_assignments, only: [:update]

  get 'posts/filter' => 'posts#filter'

  resources :posts

  resources :users

  resources :memberships

  resources :cohorts do 
    resources :schedules
  end

  post 'generate_blog_rotation' => 'schedules#generate_blog_rotation'

  post 'schedules/update_holidays' => 'schedules#update_holidays'

  post 'get_new_posts' => 'cohorts#get_new_posts'

  get 'get_new_posts_for_user' => 'users#get_new_posts'

  patch 'blogs/:id/reset' => 'blogs#reset', as: 'reset_blog'

  post 'set_blog_rotation' => 'schedules#set_blog_rotation'

  match 'login', to: redirect('/auth/github'), via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  
  get 'logout' => 'sessions#destroy'

  get 'publish_post' => 'posts#publish_post'

  get 'feature_post' => 'posts#feature_post'

  get 'publish_posts' => 'posts#publish_posts'

  post 'set_default_holidays' => 'holidays#set_default_holidays'

end

app/views/layouts/_navbar.html.erb
<nav class="nav navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
      <%= link_to 'Blogger', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <% if current_user %>

          <li><%= link_to "Hi #{current_user.first_name_or_github_name}! See your profile.", user_path(current_user) %></li>

          <%# if current_user.admin %>

            <li><%= link_to 'Admin Dashboard', cohorts_path %></li>
            <li><%= link_to 'All Users', users_path %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Schedules 
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <% Cohort.all.each.with_index do |cohort, index| %>
                  <li>
                    <%= link_to cohort.name, cohort_path(cohort) %>
                    <ul>
                    <% cohort.schedules.each do |schedule| %>
                      <%= link_to cohort_schedule_path(cohort, schedule) do %>
                        <li><%= schedule.name %></li>
                      <% end %>
                    <% end %>
                    </ul>
                  </li>
                  
                  <% if index < Cohort.count - 1 %>
                    <li class="divider"></li>
                  <% end %>
                <% end %>
              </ul>
            </li>

          <%# end %>

          <li><%= link_to 'Magazine', posts_path %></li>
          <li><%= link_to 'Sign Out', logout_path %></li>
          
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= include_gon(:init => true) %>
  <%= Gon::Base.render_data({}) %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <%= favicon_link_tag 'blog_icon.png' %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <div id="messages">
    <%= flash_messages %>
  </div>
  <%= yield %>
</div>

</body>
</html>